#!/bin/bash
set -e

printf "\n\e[0;32m🍣   Removing build folder...\e[0m\n\n"

rm -rf build
mkdir build
mkdir build/js
mkdir build/TEMP

printf "\n\e[0;32m🍣   Copying folders...\e[0m\n\n"

cp -r docs_new/data   build/
cp -r docs_new/img    build/
cp -r docs_new/people build/
cp -r docs_new/svg    build/

printf "\n\e[0;32m🍣   Copying files...\e[0m\n\n"

cp docs_new/favicon.ico   build

printf "\n\e[0;32m🍣   Compiling and uglify optimized version...\e[0m\n\n"

cmd/reset | true
node_modules/.bin/elm make --output=TEMP/elm.js src/Main.elm --optimize
node_modules/.bin/uglifyjs TEMP/elm.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output=build/js/elm.js

printf "\n\e[0;32m🍣   Minifying...\e[0m\n\n"

cp docs_new/index-dev.html TEMP/index-dev.html
node_modules/.bin/replace '(<script class="dev-only".*</script>)' '<!-- $1 -->' TEMP/index-dev.html -m -i
node_modules/.bin/replace '<!-- prod-only (.*) -->' '$1' TEMP/index-dev.html -m -i
node_modules/.bin/html-minifier -o build/404.html TEMP/index-dev.html --minify-css --minify-js --collapse-whitespace --remove-comments --preserve-line-breaks






rm -rf build/TEMP
