#!/bin/bash
printf "\n\e[0;32m🍣   Starting elm-live..."
rm -rf elm-stuff ; rm ~/.elm/0.19.0/package/*/*/*/*.dat
elm-live/bin/elm-live.js src/Main.elm --open=true --dir=docs --start-page=index-dev.html --path-to-elm=node_modules/.bin/elm -- --debug --output=docs/js-dev/main.js
